import type { Stamp, Collection } from './types'

export const mockStamps: Stamp[] = [
  {
    id: 'stamp1',
    title: 'Golden Gate at Dusk',
    imageUrl: 'https://picsum.photos/seed/stamp1/400/500',
    thumbnailUrl: 'https://picsum.photos/seed/stamp1/200/250',
    createdAt: '2024-03-15T10:30:00Z',
    sourceType: 'camera',
    sourceLabel: 'Camera Roll',
    collectionId: 'travel',
    tags: ['bridge', 'sunset', 'california'],
    dominantColor: '#F97316',
    favorite: true,
  },
  {
    id: 'stamp2',
    title: 'Forest Morning',
    imageUrl: 'https://picsum.photos/seed/stamp2/400/500',
    thumbnailUrl: 'https://picsum.photos/seed/stamp2/200/250',
    createdAt: '2024-03-14T08:15:00Z',
    sourceType: 'image',
    sourceLabel: 'Photo Library',
    collectionId: 'featured',
    tags: ['nature', 'trees', 'morning'],
    dominantColor: '#4ADE80',
    favorite: false,
  },
  {
    id: 'stamp3',
    title: 'City Lights',
    imageUrl: 'https://picsum.photos/seed/stamp3/400/500',
    thumbnailUrl: 'https://picsum.photos/seed/stamp3/200/250',
    createdAt: '2024-03-13T22:00:00Z',
    sourceType: 'camera',
    sourceLabel: 'Camera',
    collectionId: 'shots',
    tags: ['city', 'night', 'urban'],
    dominantColor: '#60A5FA',
    favorite: true,
  },
  {
    id: 'stamp4',
    title: 'Purple Mountains',
    imageUrl: 'https://picsum.photos/seed/stamp4/400/500',
    thumbnailUrl: 'https://picsum.photos/seed/stamp4/200/250',
    createdAt: '2024-03-12T16:45:00Z',
    sourceType: 'import',
    sourceLabel: 'Imported',
    collectionId: 'travel',
    tags: ['mountains', 'landscape', 'purple'],
    dominantColor: '#A78BFA',
    favorite: false,
  },
  {
    id: 'stamp5',
    title: 'Ocean Waves',
    imageUrl: 'https://picsum.photos/seed/stamp5/400/500',
    thumbnailUrl: 'https://picsum.photos/seed/stamp5/200/250',
    createdAt: '2024-03-11T14:20:00Z',
    sourceType: 'camera',
    sourceLabel: 'Camera Roll',
    collectionId: 'featured',
    tags: ['ocean', 'waves', 'water'],
    dominantColor: '#60A5FA',
    favorite: true,
  },
  {
    id: 'stamp6',
    title: 'Desert Sand',
    imageUrl: 'https://picsum.photos/seed/stamp6/400/500',
    thumbnailUrl: 'https://picsum.photos/seed/stamp6/200/250',
    createdAt: '2024-03-10T11:00:00Z',
    sourceType: 'image',
    sourceLabel: 'Photo Library',
    collectionId: 'travel',
    tags: ['desert', 'sand', 'warm'],
    dominantColor: '#F97316',
    favorite: false,
  },
  {
    id: 'stamp7',
    title: 'Red Poppy Field',
    imageUrl: 'https://picsum.photos/seed/stamp7/400/500',
    thumbnailUrl: 'https://picsum.photos/seed/stamp7/200/250',
    createdAt: '2024-03-09T09:30:00Z',
    sourceType: 'camera',
    sourceLabel: 'Camera',
    collectionId: 'shots',
    tags: ['flowers', 'red', 'field'],
    dominantColor: '#EF4444',
    favorite: false,
  },
  {
    id: 'stamp8',
    title: 'Midnight Sky',
    imageUrl: 'https://picsum.photos/seed/stamp8/400/500',
    thumbnailUrl: 'https://picsum.photos/seed/stamp8/200/250',
    createdAt: '2024-03-08T23:15:00Z',
    sourceType: 'camera',
    sourceLabel: 'Night Mode',
    collectionId: 'shots',
    tags: ['stars', 'night', 'sky'],
    dominantColor: '#1E1E1C',
    favorite: true,
  },
  {
    id: 'stamp9',
    title: 'Tokyo Street',
    imageUrl: 'https://picsum.photos/seed/stamp9/400/500',
    thumbnailUrl: 'https://picsum.photos/seed/stamp9/200/250',
    createdAt: '2024-03-07T18:00:00Z',
    sourceType: 'import',
    sourceLabel: 'Trip Photos',
    collectionId: 'travel',
    tags: ['japan', 'street', 'neon'],
    dominantColor: '#EC4899',
    favorite: false,
  },
  {
    id: 'stamp10',
    title: 'Abstract Forms',
    imageUrl: 'https://picsum.photos/seed/stamp10/400/500',
    thumbnailUrl: 'https://picsum.photos/seed/stamp10/200/250',
    createdAt: '2024-03-06T15:30:00Z',
    sourceType: 'image',
    sourceLabel: 'Curated',
    collectionId: 'featured',
    tags: ['abstract', 'art', 'color'],
    dominantColor: '#A78BFA',
    favorite: true,
  },
  {
    id: 'stamp11',
    title: 'Coffee Morning',
    imageUrl: 'https://picsum.photos/seed/stamp11/400/500',
    thumbnailUrl: 'https://picsum.photos/seed/stamp11/200/250',
    createdAt: '2024-03-05T07:45:00Z',
    sourceType: 'camera',
    sourceLabel: 'Camera',
    collectionId: 'shots',
    tags: ['coffee', 'morning', 'cozy'],
    dominantColor: '#92400E',
    favorite: false,
  },
  {
    id: 'stamp12',
    title: 'Emerald Lake',
    imageUrl: 'https://picsum.photos/seed/stamp12/400/500',
    thumbnailUrl: 'https://picsum.photos/seed/stamp12/200/250',
    createdAt: '2024-03-04T13:00:00Z',
    sourceType: 'camera',
    sourceLabel: 'Camera Roll',
    collectionId: 'featured',
    tags: ['lake', 'green', 'nature'],
    dominantColor: '#4ADE80',
    favorite: true,
  },
]

export const mockCollections: Collection[] = [
  {
    id: 'featured',
    name: 'Featured',
    coverStampIds: ['stamp2', 'stamp5', 'stamp10', 'stamp12'],
    stampCount: 4,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'travel',
    name: 'Travel',
    coverStampIds: ['stamp1', 'stamp4', 'stamp6', 'stamp9'],
    stampCount: 4,
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'shots',
    name: 'Shots',
    coverStampIds: ['stamp3', 'stamp7', 'stamp8', 'stamp11'],
    stampCount: 4,
    createdAt: '2024-02-01T00:00:00Z',
  },
  {
    id: 'all',
    name: 'All Stamps',
    coverStampIds: ['stamp1', 'stamp2', 'stamp3', 'stamp4'],
    stampCount: 12,
    createdAt: '2024-01-01T00:00:00Z',
  },
]

export const demoImages = [
  { id: 'demo1', url: 'https://picsum.photos/seed/demo1/400/500' },
  { id: 'demo2', url: 'https://picsum.photos/seed/demo2/400/500' },
  { id: 'demo3', url: 'https://picsum.photos/seed/demo3/400/500' },
  { id: 'demo4', url: 'https://picsum.photos/seed/demo4/400/500' },
  { id: 'demo5', url: 'https://picsum.photos/seed/demo5/400/500' },
  { id: 'demo6', url: 'https://picsum.photos/seed/demo6/400/500' },
]
